debug git is ancestor

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -18,6 +18,21 @@ jobs:
       VERSION: ${{ steps.version.outputs.VERSION }}
     steps:
       - uses: actions/checkout@v3
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: |
+          echo "$GITHUB_CONTEXT"
+      - run: |
+          git remote -v
+          git branch -v
+      - run: |
+          if ! git merge-base --is-ancestor "$tag" origin/main; then
+            echo "# Invalid release tag [$tag] - must be on `main` branch" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+        env:
+          tag: "${{ github.event.push.branch }}"
       - uses: actions/setup-node@v3
         with:
           node-version: 18
