Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -28,6 +28,21 @@ jobs:
       - run: |
           git remote -v
           git branch -v
+          git fetch origin main:main
+          git fetch origin 1.2.0:1.2.0
+          git branch -v
+      - run: |
+          git merge-base --is-ancestor HEAD main && echo main before head
+          if ! git merge-base --is-ancestor "$tag" origin/main; then
+            if git merge-base --is-ancestor origin/main "$tag"; then
+              echo "# Invalid release tag [$tag] - ahead of `main` branch" >> $GITHUB_STEP_SUMMARY
+            else
+              echo "# Invalid release tag [$tag] - must be on `main` branch" >> $GITHUB_STEP_SUMMARY
+            fi
+            exit 1
+          fi
+        env:
+          tag: "1.2.0"
       - run: |
           git merge-base --is-ancestor HEAD main && echo main before head
           if ! git merge-base --is-ancestor "$tag" origin/main; then
